name: Mover la tarjeta del pull request a "En desarrollo"

on:
  pull_request:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Features
          column: En desarrollo
          repo-token: ${{ secrets.GHTOKEN }}
