# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
        
    # - run: npm ci
    # - run: npm run build --if-present

    # - name: Build, Push and Release a Docker container to Heroku. 
    #   uses: gonuit/heroku-docker-deploy@v1.3.3
    #   with:
    #     email: ${{ secrets.HEROKU_EMAIL }}
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

    # - uses: matt-ball/newman-action@master
    #   with:
    #     apiKey: ${{ secrets.POSTMAN_API_KEY }}
    #     collection: ${{ secrets.POSTMAN_COLLECTION }}
    #     environment: ${{ secrets.POSTMAN_ENVIRONMENT }}

    - name: Merge test -> main
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: test
        target_branch: main
        github_token: ${{ github.token }}

    - uses: HiromiShikata/gh-actions-move-all-cards-on-projects@v1.0.1
      with:
        project_name: Features
        from_column_name: Desplegado en Testing
        to_column_name: Desplegado en Produccion
        github_token: ${{ github.token }}
