name: Create PR

on:
  push:
    branches: [ 'feature/*']

jobs:
  pr-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "Pull ${{ github.ref_name }} into main"
        pr_body: ":crown: *PR Automatizado por la action"
        github_token: ${{ secrets.GITHUB_TOKEN }}
