name: Crear PR de funcionalidad

on:
  push:
    branches: [ 'feature/*']

jobs:
  pr-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
