name: Move assigned pull requests into Testing

on:
  pull_request:
    types: [closed]

jobs:
  if_merged:
    automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Features
          column: Testing
          repo-token: ${{ secrets.GITHUB_TOKEN }}
